name: build-test

on: push

jobs:
  linux-build:
    name: Linux Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: linux-build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./main

  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: window-build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build
          main 
